/**
 * Produce the ready-to-send copy of the Pyth support letter.
 *
 *   npm run pyth-letter
 *
 * Reads the template at `docs/pyth_support_request.md`, substitutes the API
 * key from `frontend/.env.local`, and writes
 * `docs/pyth_support_request.filled.md`, which is gitignored.
 *
 * Two files rather than one because the template is committed and the key is
 * a credential. Deleting a committed secret does not remove it from git
 * history, so it never goes in in the first place; this keeps the letter
 * under version control and the key out of it.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { hermes } from './lib/env.js';

const TEMPLATE = 'docs/pyth_support_request.md';
const OUT = 'docs/pyth_support_request.filled.md';

function main() {
  const { key } = hermes();
  const template = readFileSync(TEMPLATE, 'utf8');

  // Drop the note about the filled copy: this is the filled copy.
  const body = template
    .replace(
      /^Send to .*?\n\nThe ready-to-send copy[\s\S]*?the line\.\n\n/m,
      'Send to support@pyth.network, copying data@dourolabs.xyz.\n\n' +
        'Generated by scripts/pyth_letter.ts. Contains the API key, so it is\n' +
        'gitignored. Do not commit it.\n\n',
    )
    .replace('API key: [see the filled copy]', `API key: ${key}`);

  if (!body.includes(key)) {
    throw new Error(`Could not find the API key placeholder in ${TEMPLATE}.`);
  }

  writeFileSync(OUT, body);
  console.log(`Wrote ${OUT} (gitignored). Paste it into an email as-is.`);
  console.log('Still to fill in by hand: your name at the end.');
}

main();
