/**
 * The devnet deployment, as addresses.
 *
 * `devnet.json` beside this file is generated by
 * `scripts/sync_frontend_devnet.ts` at the repo root and must not be edited
 * by hand. Regenerate it with `npm run devnet:sync` after anything that
 * changes the deployment.
 *
 * Nothing in here is a *reading*: no balance, price or weight. Those are read
 * live from the chain by `/api/devnet`, so a stale checkout renders stale
 * addresses rather than stale numbers, and a wrong address shows up as a
 * missing account instead of a plausible lie.
 */
import raw from './devnet.json';

export interface DevnetWrapper {
  key: string;
  /** The mainnet wrapper this mock stands in for, for display. */
  standsFor: string;
  /** Its `key` in `vaults.ts`, so the page can join the two registries. */
  mainnetKey: string;
  mint: string;
  decimals: number;
  multiplierSource: string;
  /** The Scaled UI multiplier the mint was created with, where it has one. */
  initialMultiplier: number | null;
  targetWeightBps: number;
  /** The Pyth feed the depeg check reads for this holding, if one exists. */
  wrapperFeedId: string | null;
  /** Where that feed's price is posted on chain. */
  wrapperPriceAccount: string | null;
  rrFeedId: string | null;
  rrPriceAccount: string | null;
  /** The vault's PDA-owned holding account for this wrapper. */
  tokenAccount: string;
  wrapperConfig: string;
}

export interface DevnetVault {
  symbol: string;
  vault: string;
  indexMint: string;
  maxWeightBps: number;
  priceAccount: string | null;
  /** The Pyth feed id, so the reader can tell a sponsored account from ours. */
  feedId: string;
  feedLabel: string;
  /** Null when devnet reads the same feed mainnet would; a reason otherwise. */
  standIn: string | null;
  wrappers: DevnetWrapper[];
}

/** One liquidity pool on the SPL Token Swap program. */
/**
 * A pool on the SPL Token Swap program, which is where everything trades
 * except the two Token-2022 holdings. Older records carry no `kind`, so an
 * absent one means this.
 */
export interface TokenSwapPool {
  kind?: 'tokenSwap';
  swapAccount: string;
  authority: string;
  poolMint: string;
  tokenA: string;
  tokenB: string;
  mintA: string;
  mintB: string;
  feeAccount: string;
  programA: string;
  programB: string;
  decimalsA: number;
}

/**
 * A pool on Raydium's CPMM, which takes a token program per side and so can
 * hold the Scaled UI mints the Token Swap build rejects.
 *
 * The sides are numbered rather than named because the program derives the
 * pool address from the two mints in pubkey order and accepts no other
 * arrangement. Which side is the holding is worked out from the mint.
 */
export interface CpmmPool {
  kind: 'cpmm';
  pair: string;
  poolId: string;
  ammConfig: string;
  observation: string;
  lpMint: string;
  mint0: string;
  mint1: string;
  vault0: string;
  vault1: string;
  program0: string;
  program1: string;
  decimals0: number;
  decimals1: number;
}

export type DevnetPool = TokenSwapPool | CpmmPool;

export function isCpmm(pool: DevnetPool): pool is CpmmPool {
  return pool.kind === 'cpmm';
}

export interface Devnet {
  cluster: string;
  programId: string;
  authority: string;
  deployedAt: string;
  vaults: DevnetVault[];
  /** The mock dollar every pool is priced against. */
  usdcMint: string | null;
  /** Pools by `<holding>-mUSDC`. */
  pools: Record<string, DevnetPool>;
}

export const DEVNET = raw as unknown as Devnet;

/**
 * True when a holding's "own" price feed is the vault's underlying.
 *
 * Three issuers publish no Pyth feed for their token, so those wrappers are
 * pointed at the feed for the asset itself. The depeg check still runs and
 * still returns a number, but it is comparing a price against itself and can
 * only ever return zero. Treating that zero as evidence the holding is
 * trading in line is the mistake this exists to prevent.
 */
export function comparesAgainstItself(vaultSymbol: string, legKey: string): boolean {
  const v = DEVNET.vaults.find((x) => x.symbol === vaultSymbol);
  const w = v?.wrappers.find((x) => x.key === legKey);
  return !!w?.wrapperFeedId && w.wrapperFeedId === v?.feedId;
}

export const EXPLORER = (address: string) =>
  `https://explorer.solana.com/address/${address}?cluster=devnet`;
